## 简介与安装

什么是机器学习

![image-20211108181813075](Start-Up.imgs/image-20211108181813075.png)

pytorch增长速度比较快，应用于学术界的比较多。

tensorflow每次更新的时候会变化很多东西，难以适应。

keras比较简单，已经整合到了tensorflow中，caffe2整合到了pytorch中。

**什么是PyTorch？**

- PyTorch是一个开源的Python机器学习库，基于Torch，用于自然语言处理，计算机视觉等应用程序。
- 2017年1月，由Facebook人工智能研究院（FAIR）基于Torch推出了PyTorch。

**PyTorch的优点是什么？**

（1）PyTorch是相当简洁且高效快速的框架，入门简单；

（2）动态计算图：PyTorch为我们提供了一个框架，以便可以在运行时构建计算图，甚至在运行时更改它们。

（3）多gpu支持，自定义数据加载器和简化的预处理器。



## 认识Tensor

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

**什么是tensor？**

scalar（标量）：一个数值

vector（向量）：一维数组

matrix（矩阵）：二维数组[[2，3]，[4，5]]

tensor（张量）：大于二维的数组，即多维数


In [1]:
import torch

In [2]:
x = [2, 9, 5, 4, 2, 1]

In [3]:
#1. 检查x是否为tensor对象

torch.is_tensor(x)

False

In [4]:
y = torch.rand(1, 2)
y

tensor([[0.1031, 0.2955]])

In [5]:
torch.is_tensor(y)

True

In [7]:
# 统计tensor中元素的个数

torch.numel(y)

2

In [9]:
# 2. 创建全0的tensor

z = torch.zeros(3, 3)

In [10]:
torch.numel(z)

9

In [11]:
# 3. 创建对角线为1的tensor

torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
# 4将numpy转换为tenosr

x = np.array([1, 5, 7, 8, 9, 3])
x

array([1, 5, 7, 8, 9, 3])

In [14]:
torch.from_numpy(x)

tensor([1, 5, 7, 8, 9, 3], dtype=torch.int32)

In [18]:
# 5 切分 linspace

torch.linspace(2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [19]:
# 6 创建均匀分布

torch.rand(10)

tensor([0.1329, 0.1351, 0.9775, 0.7463, 0.5243, 0.3739, 0.4334, 0.1318, 0.6447,
        0.0866])

In [20]:
# 7 创建正态分布

torch.randn(10)

tensor([-0.7202,  0.8905, -0.4364, -1.5051,  0.8515,  0.2801, -0.2492,  0.3015,
         0.0855, -1.6630])

In [21]:
# 8 随机数

torch.randperm(10)
# 10 表示0-10之间10个随机的数

tensor([0, 9, 3, 4, 6, 1, 7, 2, 8, 5])

In [22]:
# 9 生成一个区间的数

torch.arange(10, 30, 5)

tensor([10, 15, 20, 25])

In [24]:
# 10 获取行或列的最小值或者最大值的索引

x = torch.randint(1,99,(3, 3))
x

tensor([[74, 12, 15],
        [90, 74, 19],
        [34, 23, 12]])

In [25]:
torch.argmin(x, dim=0) # 每一列的最小值的索引

tensor([2, 0, 2])

In [27]:
torch.argmax(x, dim=1) # 每一行的最大值的索引

tensor([0, 0, 0])

In [29]:
# 11 连接

x = torch.randint(1, 10, (2, 3))
x

tensor([[7, 8, 7],
        [9, 4, 3]])

In [30]:
torch.cat([x, x]) # 按照竖轴连接

tensor([[7, 8, 7],
        [9, 4, 3],
        [7, 8, 7],
        [9, 4, 3]])

In [31]:
torch.cat([x, x], dim=1) # 1是横轴

tensor([[7, 8, 7, 7, 8, 7],
        [9, 4, 3, 9, 4, 3]])

In [33]:
# 12 切块
a = torch.randint(1, 10, (3, 3))
a

tensor([[7, 9, 7],
        [6, 1, 8],
        [7, 6, 5]])

In [34]:
torch.chunk(a, 2, 0)

(tensor([[7, 9, 7],
         [6, 1, 8]]),
 tensor([[7, 6, 5]]))

In [35]:
torch.chunk(a, 2, 1)

(tensor([[7, 9],
         [6, 1],
         [7, 6]]),
 tensor([[7],
         [8],
         [5]]))

In [36]:
# 13 index_select根据索引选择
x = torch.randn(4, 4)
x

tensor([[-1.5754, -0.3045, -1.2501,  1.5251],
        [-0.4488,  0.4039,  0.0377, -0.3522],
        [ 0.8883,  1.3149, -1.9600, -0.1154],
        [ 1.1164,  1.0829,  1.1300, -1.0247]])

In [37]:
indices = torch.tensor([0, 2])

In [38]:
torch.index_select(x, 0, indices) # 第0行和第2行

tensor([[-1.5754, -0.3045, -1.2501,  1.5251],
        [ 0.8883,  1.3149, -1.9600, -0.1154]])

In [39]:
torch.index_select(x, 1, indices) # 第0列和第2列

tensor([[-1.5754, -1.2501],
        [-0.4488,  0.0377],
        [ 0.8883, -1.9600],
        [ 1.1164,  1.1300]])

In [43]:
# 14 split 分割
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
torch.split(x, 3)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]), tensor([10]))

In [46]:
# 15 转置
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [47]:
x.t()

tensor([[1, 3],
        [2, 4]])

In [49]:
x.transpose(1, 0)

tensor([[1, 3],
        [2, 4]])

In [51]:
# 16 运算
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [52]:
torch.add(x, 1)

tensor([[2, 3],
        [4, 5]])

In [53]:
torch.mul(x, 2)

tensor([[2, 4],
        [6, 8]])

## 手写数字识别 Mnist

输入数字图片 -> 网络模型处理 -> 输出识别结果

**MNIST数据集是什么？**

- 该数据集包含60，000个用于训练的示例和10，000个用于测试的示例。
- 数据集包含了0-9共10类手写数字图片，每张图片都做了尺寸归一化，都是28×28大小的灰度图。

图片都是经过特殊处理的二进制文件，不能直接读写

手写字体的识别流程

1. 定义超参数；
2. 构建transforms，主要是对图像做变换；
3. 下载、加载数据集MNIST；
4. 构建网络模型；
5. 定义训练方法；
6. 定义测试方法；
7. 开始训练模型，输出预测结果；

专业名词解释

1. 参数与超参数。参数：模型f（x，）中的0称为模型的参数，可以通过优化算法进行学习；超参数：用来定义模型结构或优化策略。

2. batch_size批处理时每次处理的数据数量。

3. epoch轮次。把一个数据集，循环运行几轮。

4. transforms变换。主要是将图片转换为tensor，旋转图片，以及正则化。

5. nomalize正则化。模型出现过拟合现象时，降低模型复杂度。

6. 卷积层。由卷积核构建，卷积核简称为卷积，也称为滤波器。卷积的大小可以在实际需要时自定义其长和宽（1\*1，3\*3，5\*5）。

7. 池化层。对图片进行压缩（降采样）的一种方法，如max pooling，average pooling等。

8. 激活层。激活函数的作用就是，在所有的隐藏层之间添加一个激活函数，这样的输给就是一个非线性雷数了，因而神经网络的表达能力黄加强天了”

9. 损失函数。在深度学习中，损失反映模型最后预测结果与实际真值之间的差距，可以用来分析训练过程的好坏、模型是否收敛等，例如均方损失、交叉熵损失

[具体过程](./number-detect.ipynb)